# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: manifest.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'manifest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emanifest.proto\"$\n\x08Manifest\x12\x18\n\x05\x66iles\x18\x01 \x03(\x0b\x32\t.FileInfo\"b\n\x08\x46ileInfo\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x1a\n\x06\x63hunks\x18\x02 \x03(\x0b\x32\n.ChunkInfo\x12\r\n\x05\x66lags\x18\x03 \x01(\x05\x12\x0c\n\x04size\x18\x04 \x01(\x05\x12\x0b\n\x03md5\x18\x05 \x01(\t\"~\n\tChunkInfo\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\x12\x0b\n\x03md5\x18\x02 \x01(\t\x12\x0e\n\x06offset\x18\x03 \x01(\x04\x12\x17\n\x0f\x63ompressed_size\x18\x04 \x01(\r\x12\x19\n\x11uncompressed_size\x18\x05 \x01(\r\x12\x0e\n\x06xxhash\x18\x06 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'manifest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MANIFEST']._serialized_start=18
  _globals['_MANIFEST']._serialized_end=54
  _globals['_FILEINFO']._serialized_start=56
  _globals['_FILEINFO']._serialized_end=154
  _globals['_CHUNKINFO']._serialized_start=156
  _globals['_CHUNKINFO']._serialized_end=282
# @@protoc_insertion_point(module_scope)
