# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: manifest_ldiff.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'manifest_ldiff.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14manifest_ldiff.proto\"O\n\x0c\x44iffManifest\x12\x1c\n\x05\x66iles\x18\x01 \x03(\x0b\x32\r.DiffFileInfo\x12!\n\x0c\x66iles_delete\x18\x02 \x03(\x0b\x32\x0b.DeleteFile\"U\n\x0c\x44iffFileInfo\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12\x0c\n\x04hash\x18\x03 \x01(\t\x12\x17\n\x07patches\x18\x04 \x03(\x0b\x32\x06.Patch\".\n\x05Patch\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x18\n\x04info\x18\x02 \x01(\x0b\x32\n.PatchInfo\"\xd5\x01\n\tPatchInfo\x12\x10\n\x08patch_id\x18\x01 \x01(\t\x12\x0b\n\x03tag\x18\x02 \x01(\t\x12\x10\n\x08\x62uild_id\x18\x03 \x01(\t\x12\x12\n\npatch_size\x18\x04 \x01(\x03\x12\x12\n\npatch_name\x18\x05 \x01(\t\x12\x14\n\x0cpatch_offset\x18\x06 \x01(\x03\x12\x14\n\x0cpatch_length\x18\x07 \x01(\x03\x12\x15\n\roriginal_name\x18\x08 \x01(\t\x12\x15\n\roriginal_size\x18\t \x01(\x03\x12\x15\n\roriginal_hash\x18\n \x01(\t\"5\n\nDeleteFile\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x04info\x18\x02 \x01(\x0b\x32\x0c.DeleteFiles\",\n\x0b\x44\x65leteFiles\x12\x1d\n\x04list\x18\x01 \x03(\x0b\x32\x0f.DeleteFileInfo\">\n\x0e\x44\x65leteFileInfo\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x03\x12\x0c\n\x04hash\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'manifest_ldiff_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DIFFMANIFEST']._serialized_start=24
  _globals['_DIFFMANIFEST']._serialized_end=103
  _globals['_DIFFFILEINFO']._serialized_start=105
  _globals['_DIFFFILEINFO']._serialized_end=190
  _globals['_PATCH']._serialized_start=192
  _globals['_PATCH']._serialized_end=238
  _globals['_PATCHINFO']._serialized_start=241
  _globals['_PATCHINFO']._serialized_end=454
  _globals['_DELETEFILE']._serialized_start=456
  _globals['_DELETEFILE']._serialized_end=509
  _globals['_DELETEFILES']._serialized_start=511
  _globals['_DELETEFILES']._serialized_end=555
  _globals['_DELETEFILEINFO']._serialized_start=557
  _globals['_DELETEFILEINFO']._serialized_end=619
# @@protoc_insertion_point(module_scope)
